@host=http://localhost:5126

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZmQ2ZDI4OS0wMmY3LTQ1M2YtOGYzMC1lMWZhODZhN2JjMWEiLCJnaXZlbl9uYW1lIjoiSm9obm5uIiwiZmFtaWx5X25hbWUiOiJEb2UiLCJqdGkiOiIxOWNlNzJjMi01MjQ0LTQ1NmYtOGMwNy1kNzQwMWI5NDgzNTIiLCJleHAiOjE3NTExMjU3MTYsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXJVc2VycyJ9.Zfmv2kZ4yLqJh9UeFUGdgwwKIiJZAGSRT7RnqRdkqrQ
